<?php

namespace AppBundle\Repository;

/**
 * AddressTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
