<?php

namespace AppBundle\Repository;

/**
 * AllergiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllergiesRepository extends \Doctrine\ORM\EntityRepository
{
}
