<?php

namespace AppBundle\Repository;

/**
 * EmailTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
