<?php

namespace AppBundle\Repository;

/**
 * PatientTelephonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientTelephonesRepository extends \Doctrine\ORM\EntityRepository
{
}
