<?php

namespace AppBundle\Repository;

/**
 * PatientOperationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientOperationsRepository extends \Doctrine\ORM\EntityRepository
{
}
