<?php

namespace AppBundle\Repository;

/**
 * PatientAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
