<?php

namespace AppBundle\Repository;

/**
 * PatientEmailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientEmailsRepository extends \Doctrine\ORM\EntityRepository
{
}
