<?php

namespace AppBundle\Repository;

/**
 * PatientDiseasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientDiseasesRepository extends \Doctrine\ORM\EntityRepository
{
}
