<?php

namespace AppBundle\Repository;

/**
 * PatientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientsRepository extends \Doctrine\ORM\EntityRepository
{
    public function get_patient_name($patient_id){
        $patient_name = '';
        $patient = $this->find($patient_id);
        
        return $patient;
    }
}
