<?php

namespace AppBundle\Repository;

/**
 * PatientAllergiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientAllergiesRepository extends \Doctrine\ORM\EntityRepository
{
}
