<?php

namespace AppBundle\Repository;

/**
 * TelephoneTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelephoneTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
