<?php

namespace AppBundle\Repository;

/**
 * WaitingListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaitingListRepository extends \Doctrine\ORM\EntityRepository
{
}
